---
- name: Cisco Router Port Configuration
  connection: network_cli
  gather_facts:
  hosts: Cisco_Router

  tasks:
    - name: show int
      ios_command:
        commands:
        - command: show interfaces
      register: result

    - name: show run
      ios_command: 
        commands: 
        - command: show running-config 
      register: result

    - name: Port FastEthernet0/1 configuration      
      cisco.ios.ios_l2_interfaces:
              name: FastEthernet0/1
              mode: trunk
              trunk_allowed_vlans: 10-20

