---
- name: Cisco Router Port Configuration
  connection: network_cli
  gather_facts:
  hosts: Cisco_Router

  tasks:
    - name: show int
      ios_command:
        commands:
        - command: show interfaces
      register: result

    - name: show run
      ios_command: 
        commands: 
        - command: show running-config 
      register: result

    - name: Port FastEthernet0/1 configuration      
      ios_config:
        parents: "interface FastEthernet0/1"
        lines:
          - description viru-test
          - ip address 192.168.100.249 255.255.255.0
          - no shutdown 
